//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBA1.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int LinkId { get; set; }
        public string OriginLink { get; set; }
        public string ShortedLink { get; set; }
        public string Login { get; set; }
        public bool IsActive { get; set; }
        public int Redirections { get; set; }
        public int GroupId { get; set; }
    }
}
